### ISSUE TITLE
How can I reach you?

### ISSUE THREAD

**Issue by radiumrasheed** [thexande/ng_movie_search#1]
Hi @thexande, I've been trying to reach you.

Please respond to my messages or mail 🙏🏼

**Comment by radiumrasheed** [comment]
hello @thexande

**Comment by CLClark1995** [comment]
@radiumrasheed Hey! Hope all is well. I believe he has a linkedn. Message him on there. I was actually going to message him as I believe I discovered a bug in his app. A small one.

**Comment by radiumrasheed** [comment]
thanks @CLClark1995 
Well, it's so all can be well 

I did reach out on LinkedIn too
